name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: desafiobraviapi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./Desafio.Bravi.Api.sln
      
      - name: Build
        run: dotnet build ./Desafio.Bravi.Api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Desafio.Bravi.Api.sln --configuration Release --no-build
  
      - name: Deployment
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
